/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package gui;

import estructuras.FIFO;
import javax.swing.JOptionPane;

/**
 *
 * @author jra
 */
public class PanelBotonesFIFO extends
        javax.swing.JPanel {

    private PanelLibro pnlformulario;
    private PanelElementos pnlElementos;
    private FIFO cola;

    /**
     * Creates new form PanelAccionesLIFO
     */
    public PanelBotonesFIFO() {
        initComponents();
    }

    public PanelBotonesFIFO(PanelLibro pnlformulario, PanelElementos pnlElementos) {
        initComponents();
        this.pnlformulario = pnlformulario;
        this.pnlElementos = pnlElementos;
        cola = new FIFO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed"
//    desc  = "Generated Code" >

    private void initComponents() {
        btnEnqueue = new javax.swing.JButton();
        btnDequeue = new javax.swing.JButton();
        btnPeek = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        setLayout(new javax.swing.BoxLayout(this,
                javax.swing.BoxLayout.PAGE_AXIS));
        btnEnqueue.setText("ENQUEUE");
        btnEnqueue.addActionListener(this::btnEnqueueActionPerformed);
        add(btnEnqueue);
        btnDequeue.setText("DEQUEUE");
        btnDequeue.addActionListener(this::btnDequeueActionPerformed);
        add(btnDequeue);
        btnPeek.setText("PEEK");
        btnPeek.addActionListener(this::btnPeekActionPerformed);
        add(btnPeek);
        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);
        add(btnClear);
    }// </editor-fold>

    private void btnEnqueueActionPerformed(java.awt.event.ActionEvent evt) {
        if (pnlformulario.libro == null) {
            JOptionPane.showMessageDialog(this, "el libro debe estar creado antes de aplicar");
        } else {
            cola.enqueue(pnlformulario.libro);
            JOptionPane.showMessageDialog(this, "libro agregado a cola");
            pnlElementos.txtElementos.setText(cola.showQueue());
            pnlformulario.libro = null;
        }
    }

    private void btnDequeueActionPerformed(java.awt.event.ActionEvent evt) {
        if (cola.isEmpty()) {
            JOptionPane.showMessageDialog(this, "la cola esta vacia");
        } else {
            JOptionPane.showMessageDialog(this, cola.dequeue());
            pnlElementos.txtElementos.setText(cola.showQueue());
        }
    }

    private void btnPeekActionPerformed(java.awt.event.ActionEvent evt) {
        if (cola.isEmpty()) {
            JOptionPane.showMessageDialog(this, "la cola esta vacia");
        } else {
            JOptionPane.showMessageDialog(this, cola.peek());
        }
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        if (cola.isEmpty()) {
            JOptionPane.showMessageDialog(this, "la cola esta vacia");
        } else {
            cola.clear();
            pnlElementos.txtElementos.setText(cola.showQueue());
        }
    }
    // Variables declaration - do not modify
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDequeue;
    private javax.swing.JButton btnEnqueue;
    private javax.swing.JButton btnPeek;
// End of variables declaration
}
