/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package gui;

/**
 *
 * @author jra
 */
public class PanelElementos extends javax.swing.JPanel {

    /**
     * Creates new form PanelElementos
     */
    public PanelElementos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed"  desc  = "Generated Code" >

    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        txtElementos = new javax.swing.JTextArea();
        setLayout(new java.awt.BorderLayout());
        txtElementos.setColumns(20);
        txtElementos.setRows(5);
        jScrollPane1.setViewportView(txtElementos);
        add(jScrollPane1,
                java.awt.BorderLayout.CENTER);
    }// </editor-fold>
// Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtElementos;
// End of variables declaration
}
