/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package gui;

import common.Libro;
import javax.swing.JOptionPane;

/**
 *
 * @author jra
 */
public class PanelLibro extends javax.swing.JPanel {

    public Libro libro;

    /**
     * Creates new form PanelLibro
     */
    public PanelLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed"
//    desc  = "Generated Code" >

    private void initComponents() {
        btnNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAñopublicacion = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        btnCargarImagen = new javax.swing.JButton();
        txtLibro = new javax.swing.JLabel();
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        jLabel1.setText("Titulo");
        jLabel2.setText("Autor");
        jLabel3.setText("Año publicacion");
        txtTitulo.addActionListener(this::txtTituloActionPerformed);
        txtAñopublicacion.addActionListener(this::txtAñopublicacionActionPerformed);
        lblImagen.setText("IMAGEN");
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCargarImagen.setText("Cargar imagen");
        btnCargarImagen.addActionListener(this::btnCargarImagenActionPerformed);
        txtLibro.setText("LIBRO");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(68, 68, 68)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel1))
                                                                .addGap(51, 51, 51)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtTitulo,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtAutor,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)
                                                                .addGap(51, 51, 51)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnNuevo)
                                                                        .addComponent(txtAñopublicacion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(26, 26, 26))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(txtLibro)
                                                        .addGap(45, 45, 45)
                                        ))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCargarImagen)
                                        .addComponent(lblImagen,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                135,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(68,
                                        Short.MAX_VALUE)
                        )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtLibro)
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(txtTitulo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtAutor,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE
                                                )
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnCargarImagen)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(txtAñopublicacion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnNuevo)))
                                        )
                                        .addComponent(lblImagen,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                140,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                )
                                .addGap(168, 168, 168)
                        )
        );
    }// </editor-fold>

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {
        this.libro = new Libro();
        this.libro.setTitulo(txtTitulo.getText());
        this.libro.setAutor(txtAutor.getText());
        this.libro.setAnio(Integer.parseInt(txtAñopublicacion.getText()));
        JOptionPane.showMessageDialog(this, "libro creado");
        JOptionPane.showMessageDialog(this, libro);
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAñopublicacion.setText("");
    }

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
    }

    private void txtAñopublicacionActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
    }

    private void
            btnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
    }
// Variables declaration - do not modify
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblImagen;
    public javax.swing.JTextField txtAutor;
    public javax.swing.JTextField txtAñopublicacion;
    private javax.swing.JLabel txtLibro;
    public javax.swing.JTextField txtTitulo;
// End of variables declaration
}
