/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

import back.estructura.Arista;
import back.estructura.Grafo;
import back.modelo.Nodo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author jra
 */
public class Lienzo extends javax.swing.JPanel implements MouseListener, MouseMotionListener{

    private Grafo grafo;
    private Nodo nodoSeleccionado = null;
    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Dibujar aristas
//        for (Arista a : grafo.aristas) {
//            g.drawLine(a.origen.x, a.origen.y, a.destino.x, a.destino.y);
//        }

        // Dibujar nodos
        for (Nodo n : grafo.getNodos()) {
            g.setColor(Color.BLUE);
            g.fillOval(n.x - 15, n.y - 15, 30, 30);
            g.setColor(Color.WHITE);
            g.drawString(n.getCiudad().getNombre(), n.x - 4, n.y + 4);
            for (Arista a : n.getAristas()) {
                g.drawLine(n.x, n.y, a.getDestino().x, a.getDestino().y);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

        // =============================
    // EVENTOS MOUSE
    // =============================

    @Override
    public void mousePressed(MouseEvent e) {
        for (Nodo n : grafo.getNodos()) {
            if (Math.hypot(e.getX() - n.x, e.getY() - n.y) < 15) {
                nodoSeleccionado = n;
                return;
            }
        }
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        if (nodoSeleccionado != null) {
            nodoSeleccionado.x = e.getX();
            nodoSeleccionado.y = e.getY();
            repaint();
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        nodoSeleccionado = null;
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        // Si no se hizo click sobre un nodo, crear uno nuevo
        boolean sobreNodo = false;

        for (Nodo n : grafo.getNodos()) {
            if (Math.hypot(e.getX() - n.x, e.getY() - n.y) < 15) {
                sobreNodo = true;
                break;
            }
        }

        if (!sobreNodo) {
//            grafo.nuevoNodo(e.getX(), e.getY(), );
            repaint();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
